import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderComponents from "@/components/HeaderComponents";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {title: "Create Next App",
  description: "Generated by create next app",
};

type PropType = {children:React.ReactNode};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={inter.className}>

      <HeaderComponents/>
      {children}


      </body>
     </html>
  );
}
